services:
  singbox:
    tty: true
    stdin_open: true
    container_name: singbox-client
    image: swr.cn-east-3.myhuaweicloud.com/iflyelf/singbox-client:latest
    command: []
    pid: host
    ipc: host
    privileged: true
    restart: always
    cap_add:
      - ALL
    volumes:
      - ./conf/config.json:/etc/sing-box/config.json:ro,cached
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro,cached
      - /etc/localtime:/etc/localtime:ro,cached
      - /sys/fs/bpf:/sys/fs/bpf:rw,cached
      - /lib/modules:/lib/modules:ro,cached
      - /etc/sysctl.conf:/etc/sysctl.conf:ro,cached
    devices:
      - /dev/net/tun
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
