server {
    listen 9898;
    listen [::]:9898;
    server_name _;
    charset utf-8;
    root /www;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    }

    location ~* \.(?:css|js|woff2?|svg|gif|map|png|ico)$ {
        try_files $uri =404;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    }
}
